# Generated by Django 5.2.17 on 2026-10-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Адрес')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Кратко')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, ₽')),
                ('duration_days', models.PositiveSmallIntegerField(default=3, verbose_name='Срок, дней')),
                ('delivery_format', models.CharField(choices=[('online', 'Онлайн-встреча'), ('file', 'Файл-результат'), ('access', 'Доступ к сервису')], default='file', max_length=10, verbose_name='Формат выдачи')),
                ('cover', models.ImageField(blank=True, upload_to='services/%Y/%m/', verbose_name='Обложка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликована')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='catalog_ser_slug_1b8ff2_idx'), models.Index(fields=['is_active', 'price'], name='catalog_ser_is_acti_45df99_idx')],
            },
        ),
    ]
